# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
contact_links:
  - name: Cathode issue
    url: https://github.com/vezel-dev/cathode/issues/new/choose
    about: Open an issue related to the Cathode project on the corresponding repository.
  - name: Celerity issue
    url: https://github.com/vezel-dev/celerity/issues/new/choose
    about: Open an issue related to the Celerity project on the corresponding repository.
  - name: Minja issue
    url: https://github.com/vezel-dev/minja/issues/new/choose
    about: Open an issue related to the Minja project on the corresponding repository.
  - name: Niru issue
    url: https://github.com/vezel-dev/niru/issues/new/choose
    about: Open an issue related to the Niru project on the corresponding repository.
  - name: Novadrop issue
    url: https://github.com/vezel-dev/novadrop/issues/new/choose
    about: Open an issue related to the Novadrop project on the corresponding repository.
  - name: Ruptura issue
    url: https://github.com/vezel-dev/ruptura/issues/new/choose
    about: Open an issue related to the Ruptura project on the corresponding repository.
  - name: Zig SDK issue
    url: https://github.com/vezel-dev/zig-sdk/issues/new/choose
    about: Open an issue related to the Zig SDK project on the corresponding repository.
