# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Secrets
on:
    schedule:
        - cron: 0 0 1 1 *
permissions:
    issues: write
defaults:
    run:
        shell: bash
jobs:
    secrets:
        runs-on: ubuntu-22.04
        steps:
            - name: Create GitHub issue
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  gh issue create -R ${{ github.repository }} -t "Refresh organization secrets ($(date +%Y))" -b "It is time to refresh the \`NUGET_TOKEN\`, \`OVSX_TOKEN\`, and \`VSCE_TOKEN\` organization secrets." -l "area: marketplace" -l "area: nuget"
