# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Secrets
on:
    schedule:
        - cron: 0 0 1 1 *
    workflow_dispatch:
permissions:
    issues: write
defaults:
    run:
        shell: bash
jobs:
    secrets:
        runs-on: windows-2022
        steps:
            - name: Create GitHub issue
              run: |
                  gh issue create -R ${{ github.repository }} -t "Refresh organization secrets $(date +%Y)" -l "area: marketplace" -l "area: nuget"
